# Sample workflow for building and deploying a Next.js site to GitHub Pages
#
# To get started with Next.js see: https://nextjs.org/docs/getting-started
#
name: Deploy Next.js site to Pages

on:
  push:
    branches: ["master"]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Versioning job
  version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Get current version
        id: get_version
        run: |
          VERSION=$(jq -r .version package.json)
          echo "Current version: $VERSION"
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Determine new version
        id: determine_version
        run: |
          if git log -1 --pretty=%B | grep -q 'feat:'; then
            NEW_VERSION=$(npm version minor -m "Increment version to %s [skip ci]")
          elif git log -1 --pretty=%B | grep -q 'fix:'; then
            NEW_VERSION=$(npm version patch -m "Increment version to %s [skip ci]")
          else
            echo "No version change required"
            exit 0
          fi
          echo "New version: $NEW_VERSION"
          echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV

          # Show changes in package.json
          echo "Changes in package.json:"
          git diff package.json

      - name: Commit version change
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

          if [ -n "$(git status --porcelain)" ]; then
            git add package.json package-lock.json
            git commit -m "Bump version to ${{ env.NEW_VERSION }}"
            git push
          else
            echo "No changes to commit"
          fi

  # Build job
  build:
    runs-on: ubuntu-latest
    needs: version
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Remaining steps of your build job...
      # (This part remains the same as your existing build job)

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
